version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: camstudy-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: camstudy
      MYSQL_USER: camuser
      MYSQL_PASSWORD: campass
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    image: camstudy-app
    container_name: camstudy-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    build:
      context: .
    restart: always

volumes:
  mysql-data:
