version: "3.9"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-vl:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb_buffer_pool_size=128M
      --max_connections=50
      --table_open_cache=200
      --innodb_log_buffer_size=16M
    restart: always

  app:
    image: yejiii1997/cmas:latest
    platform: linux/amd64
    container_name: camstudy-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: always

volumes:
  mysql-vl:
    driver: local
